amcl:
  ros__parameters:
    use_sim_time: true

    # Frames
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map

    # Topics
    scan_topic: /scan

    # ---------------- Particle Filter ----------------
    min_particles: 1000
    max_particles: 3000

    # Motion model noise
    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1
    alpha5: 0.1

    # Update thresholds
    update_min_d: 0.02
    update_min_a: 0.02

    scan_queue_size: 50

    resample_interval: 1
    transform_tolerance: 0.2
    tf_broadcast: true   #added for testing of tf issue lag

    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    set_initial_pose: true

    # ---------------- Sensor Model ----------------
    laser_max_range: 100.0
    laser_min_range: 0.0
    laser_model_type: likelihood_field

    # Recovery
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
